# Generated by Django 3.1a1 on 2020-06-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200603_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
